# Run with sudo docker-compose up!!!
services:
  visual-perma-tracker-app:
    image: mo12896/visual-perma-tracker:0.0.26
    volumes:
      - /home/moritz/Workspace/masterthesis/data:/home/data
      - /home/moritz/Workspace/masterthesis/data/identities:/home/data/identities
      - /home/moritz/Workspace/masterthesis/configs:/home/configs
      - /home/moritz/Workspace/masterthesis/data/images:/home/data/images
    stdin_open: true
    tty: true
    command: python main.py
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

