VIDEO_CODEC: MP4V
VIDEO: "short_clip_debug.mp4"
DETECTION_FREQUENCY: 5
DETECTOR:
  type: scrfd
EMBEDDER:
  type: insightface
  ctx_id: 0
  det_size: 128
TRACKER:
  type: byte
EMOTION_DETECTOR:
  type: rmn
POSE_ESTIMATOR:
  type: l_openpose
HEAD_POSE_ESTIMATOR:
  type: synergy
GAZE_DETECTOR:
  fov: 60
  true_thresh: 1.0
  axis_length: 2000
ANCHOR_EMBDDINGS: "database/embeddings.db"
