VIDEO_CODEC: MP4V
VIDEO: "short_clip_debug.mp4"
DETECTION_FREQUENCY: 10
EMBEDDER:
  type: insightface
  ctx_id: 0
  det_size: 128
TRACKER:
  type: byte
EMOTION_DETECTOR:
  type: rmn
DETECTOR: retinaface
POSE_ESTIMATOR:
  type: lopenpose
ANCHOR_EMBDDINGS: "database/embeddings.db"
