VIDEO_CODEC: MP4V
DETECT_FREQ: 10
VIDEO: "short_clip.mp4"
DETECTION_FREQUENCY: 10
EMBEDDER:
  type: "insightface"
  ctx_id: 0
  det_size: 128
TRACKER:
  type: "byte"
DETECTOR: retinaface
ANCHOR_EMBDDINGS: "database/embeddings.db"
